### ISSUE TITLE
Calling Database::get($dsn, true) already opens a connection, even though it itsn't necessary

### ISSUE THREAD

**Issue by gerryd** [tigron/skeleton-database#1]
The database connection is always opened (if it isn't yet) when calling Database::get(), even if we don't actually use the resulting instance. In the Skeleton project, the database is initialized every request.

We should only connect to the database when it is really required, which can be defined as "when it is actually being used".

**Comment by christopheg** [comment]
An internal flag is created to indicate if the connection is made. A new connection will only be made when a query will be executed.
